Repository wntrblm/nox, pull requests merged in 2021-12, with the labels that each got.

#518 Update the list of maintainers
  docs/index.rst
Labels: docs

#533 Document how `session.run` fails, and how to handle failures
  nox/sessions.py
Labels: docs

#539 Fix project's noxfile sessions definition
  noxfile.py
Labels: bug

#542 ci: Enable color output from Nox, pytest, and pre-commit
  .github/workflows/ci.yml
  tests/test_main.py
Labels: ci

#547 Pin virtualenv version in lint session
  noxfile.py
Labels: bug, ci
